public class CriteriaExpressionHelper {

    // private CriteriaExpression expression;
    // private List<CriteriaExpression> andExpressions = new List<CriteriaExpression>();
    // private List<CriteriaExpression> orExpressions = new List<CriteriaExpression>();



    

    // // public CriteriaExpressionHelper() {

    // // }

    // public void addFirstExpression(String fieldName, SOQLExpressionHelper.FieldOperator fieldOperator, String fieldValue){
    //     expression = new CriteriaExpression(fieldName, fieldOperator, fieldValue);
    // }

    // public void addAndExpression(String fieldName, SOQLExpressionHelper.FieldOperator fieldOperator, String fieldValue) {
    //     andExpressions.add(new CriteriaExpression(fieldName, fieldOperator, fieldValue, SOQLExpressionHelper.CriteriaOperator.AND_CRIT));
    // }

    // public void addOrExpression(String fieldName, SOQLExpressionHelper.FieldOperator fieldOperator, String fieldValue) {
    //     andExpressions.add(new CriteriaExpression(fieldName, fieldOperator, fieldValue, SOQLExpressionHelper.CriteriaOperator.OR_CRIT));
    // }

    // public void addOrExpression(CriteriaExpression expression){

    // }
}
