public enum ContentDocumentLinkShareTypes {
    V,
    C,
    I
}


// private static String getShareTypeValue(ShareTypes shareType) {
//     String shType;
//     Switch on shareType {
//         When V {
//             shType = 'V';
//         }
//         When C {
//             shType = 'C';
//         }
//         When I {
//             shType = 'I';
//         }
//     }
//     return shType;
// }
