public class ObjectInfoWrapper {
    
    	public String objectAPIName;
        public String recordTypeDeveloperName;
        public String recordTypeId;
    
    	
        
        public void setObjectAPIName(String objectAPIName){
            this.objectAPIName = objectAPIName;
        }
    
    	public void setRecordTypeDeveloperName(String recordTypeDeveloperName){
            this.recordTypeDeveloperName = recordTypeDeveloperName;
        }
    
        public void setRecordTypeId(String recordTypeId){
            this.recordTypeId = recordTypeId;
        }
    

}