@isTest public class GetObjectInfoTest {
    
    // @isTest static void extractObjectInfoToCSV() {

    //     String title = GetObjectInfo.TITLE;

    //     Test.startTest();
    //     GetObjectInfo getO = new GetObjectInfo();
    //     getO.extractObjectInfoToCSV('WMA_Facility__c');
    //     ContentVersion contentVersion = [SELECT Id FROM ContentVersion WHERE Title =:title];
    //     Test.stopTest();

    //     System.assert(contentVersion != null);
    //     System.assert(contentVersion.Id != null);
    // }
}
