public class CriteriaExpressionBuilder {

    // private String fieldName;
    // private CriteriaExpression.FieldOperator fieldOperator;
    // private String fieldValue;
    // private CriteriaExpression.CriteriaOperator criteriaOperator;

    // // class Expression {
    // //     private String fieldName;
    // //     private CriteriaExpression.FieldOperator fieldOperator;
    // //     private String fieldValue;

    // //     public Expression(String fieldName, CriteriaExpression.FieldOperator fieldOperator, String fieldValue){
    // //         this.fieldName = fieldName;
    // //         this.fieldOperator = fieldOperator;
    // //         this.fieldValue = fieldValue;
    // //     }
    // // }

    // public CriteriaExpressionBuilder() {
    //     this.fieldName = 'Id';
    //     this.fieldOperator = CriteriaExpression.FieldOperator.EQUALS_FIELD;
    // }

    // public CriteriaExpressionBuilder setExpressionParts (String fieldName, CriteriaExpression.FieldOperator fieldOperator, String fieldValue){
    //     this.fieldName = fieldName;
    //     this.fieldOperator = fieldOperator;
    //     this.fieldValue = fieldValue;
    //     return this;
    // }

    // public CriteriaExpressionBuilder setCriteriaOperator(CriteriaExpression.CriteriaOperator criteriaOperator) {
    //     this.criteriaOperator = criteriaOperator;
    //     return this;
    // }

    // // public CriteriaExpressionBuilder setFieldName(String fieldName) {
    // //     this.fieldName = fieldName;
    // //     return this;
    // // }

    // // public CriteriaExpressionBuilder setFieldOperator(CriteriaExpression.FieldOperator fieldOperator) {
    // //     this.fieldOperator = fieldOperator;
    // //     return this;
    // // }

    // // public CriteriaExpressionBuilder setfieldValue(String fieldValue) {
    // //     this.fieldValue = fieldValue;
    // //     return this;
    // // }

    

    // public CriteriaExpression build(){
    //     return new CriteriaExpression(this.fieldName, this.fieldOperator, this.fieldValue, this.criteriaOperator);
    // }
}


// public class CriteriaExpressionBuilder {

//     private String fieldName;
//     private CriteriaExpression.FieldOperator fieldOperator;
//     private String fieldValue;
//     private CriteriaExpression.CriteriaOperator criteriaOperator;

//     public CriteriaExpressionBuilder() {
//         this.fieldName = 'Id';
//         this.fieldOperator = CriteriaExpression.FieldOperator.EQUALS_FIELD;
//     }

//     public CriteriaExpressionBuilder setFieldName(String fieldName) {
//         this.fieldName = fieldName;
//         return this;
//     }

//     public CriteriaExpressionBuilder setFieldOperator(CriteriaExpression.FieldOperator fieldOperator) {
//         this.fieldOperator = fieldOperator;
//         return this;
//     }

//     public CriteriaExpressionBuilder setfieldValue(String fieldValue) {
//         this.fieldValue = fieldValue;
//         return this;
//     }

//     public CriteriaExpressionBuilder setCriteriaOperator(CriteriaExpression.CriteriaOperator criteriaOperator) {
//         this.criteriaOperator = criteriaOperator;
//         return this;
//     }

//     public CriteriaExpression build(){
//         return new CriteriaExpression(this.fieldName, this.fieldOperator, this.fieldValue, this.criteriaOperator);
//     }
// }
